### ISSUE TITLE
Umgang mit Teamdrives funktioniert nicht

### ISSUE THREAD

**Issue by moellenbeck** [5minds/GDrive-Tools#21]
Es wird nicht das Teamdrive verwendet ;-(

```python
from time import sleep

import gdrive_tools.gdrive_tools as gt
import gdrive_tools.google_auth as ga
from gdrive_tools.google_filetypes import GoogleFiletypes

# If modifying these scopes, delete the file token.pickle.
SCOPES = ['https://www.googleapis.com/auth/documents', 'https://www.googleapis.com/auth/drive']

def main():
  auth = ga.GoogleAuth(SCOPES)
  creds = auth.createCredentials()

  # Create the google drive tools client with your local credentials.
  googleDriveTools = gt.GDriveTools(creds)

  # Create a new Google Document named 'sample' at the path 'simple/test'
  destinationPath = 'simple/test'
  docname = 'sample'
  googleDriveTools.createFile(destinationPath, docname, GoogleFiletypes.DOCUMENT)

  input("""\
There should be a new "simple" folder in your google drive root directory. \
In this folder, you can find the folder named "test" that contains the created document "sample".
Hint: If you currently opened google drive in your browser, you may have to refresh the page to see the \
changes.
Press the Return key to continue...
""")

  # Move the created document to the 'new/test' directory.
  sourcePath = 'simple/test/sample'
  destinationPath = '/__simple/new/test'
  googleDriveTools.moveDocument(sourcePath, destinationPath)

  print("""\
Now you should also find a "new" folder in your google drive root directory. \
This folder also contains a "test" folder which now contains the document \
named "sample".
Hint: You may also have to refresh your browser. \
""")

if __name__ == '__main__':
  main()
```

Ich hätte erwartet, dass die Zieldaten im Teamdrive "__simple" liegen würden. 

- Was mache ich falsch?
- Dokumentation ist nicht ausreichend.

**Comment by robpal94** [comment]
Hallo Martin,

Ich bräuchte noch ein Paar Informationen zu dem, was du versucht hast. Generell habe ich das so verstanden: 

Du hast ein Teamdrive mit dem Namen _simple_ und möchtest dort eine Datei im Ordner _/test/_ anlegen. Diese Datei soll dann in den Ordner `__simple/test` verschoben werden. Habe ich das richtig interpretiert?

**Comment by moellenbeck** [comment]
@robpal94 soweit ich es verstanden habe muss ich die Teamablage mit "/" am Anfang angeben. Daher die Angabe "destinationPath = '/__simple/new/test'" (Einladung für die Ablage ist raus).

Ziel ist eigentlich: Ich möchte ein Sheet in einer Teamablage mit einem Unterordner anlegen.

//cc @roblen45

**Comment by robpal94** [comment]
Achso, nein an sich ist der Querstrich am Anfang egal.
Wenn du einfach nur ein Sheet in einem Unterordner einer Teamablage anlegen möchtest, sollte dies mit folgender Anweisung funktionieren: 

```
destinationPath = 'NameTeamablage/NameDesUnterordners'
docname = 'NameDesSheets'
googleDriveTools.createFile(destinationPath, docname, GoogleFiletypes.DOCUMENT)
```

Danach ist auch kein Aufruf der `moveDocument()` Methode mehr nötig. Der Aufruf von `createDocument()` bewegt das entsprechende Dokument automatisch an den gewünschten Zielort. 

Es ist allerdings erforderlich, dass die Teamablage mit dem gegebenen Namen (also quasi der Angabe vor dem erstem Slash) existiert. Ansonsten wird das Dokument in den entsprechenden Unterordnern in deinem privatem Drive abgelegt.

**Comment by robpal94** [comment]
Hier noch ein Beispiel: 

![out](https://user-images.githubusercontent.com/38498731/70801012-f8dcf780-1dad-11ea-9298-b7b5ee96f66c.gif)

**Comment by robpal94** [comment]
@moellenbeck Besteht dieser Issue immer noch?

**Comment by moellenbeck** [comment]
@robpal94 ich würde das Ticket vorerst schließen
