### ISSUE TITLE
Fehler beim Auslesen eines Sheets, wenn einen Zelle leer ist.

### ISSUE THREAD

**Issue by moellenbeck** [5minds/GDrive-Tools#32]
Beispiel-Sheet ist:
- https://docs.google.com/spreadsheets/d/1A-eKWBFBzvtpZpZAeNL8KQ-BcaAP2HyahJ4x0ivcvGg/edit#gid=0

Bitte dort die Zelle B3 entfernen, dann ergibt sich folgender Fehler:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-11-9a062c3bf0a4> in <module>
----> 1 data_frame = googleDriveTools.readSheet(sheet_id, 'Daten')

~/.pyenv/versions/3.7.4/envs/jupyterlab-3.7.4/lib/python3.7/site-packages/gdrive_tools/gdrive_tools.py in readSheet(self, sheetId, sheetName, a1Range, placeholder)
    204 
    205     sheetValues = response['valueRanges'][0]['values']
--> 206     sheetAsDict = self.__generateDictFromList(sheetValues, placeholder)
    207 
    208     return sheetAsDict

~/.pyenv/versions/3.7.4/envs/jupyterlab-3.7.4/lib/python3.7/site-packages/gdrive_tools/gdrive_tools.py in __generateDictFromList(data, placeholder)
    535           dictToAppend[currentColumn] = placeholder[currentColumn]
    536         else:
--> 537           raise ValueError(f'Undefined column named "{currentColumn}" in row {rowIndex}')
    538 
    539       outList.append(dictToAppend)

ValueError: Undefined column named "Spalte 2" in row 1
```

Dies liegt daran, dass der Zugriff auf den Wert mit `placeholder[currentColumn]`anstatt mit `placeholder.get(currentColumn, None)` gemacht wird.

**Comment by robpal94** [comment]
Hallo Martin,

tatsächlich war die Exception von mir ein _erwartetes_ verhalten. Dies soll anzeigen, dass der Wert einer Zelle quasi _unerwartet_ leer ist (sprich, der Nutzer keinen Placeholder für leere Werte der entsprechenden Zelle gesetzt hat). 

Allerdings gebe ich dir recht, dass man in diesem Falle einfach einen _generellen_ Standartwert aka `None` oder vielleicht einen leeren String setzten sollte.
